## our React TodoMVC app is written
## in node so thats what we select.
## Cypress is agnostic to your apps
## backend language though.
language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run cypress:run
