## our React TodoMVC app is written
## in node so thats what we select.
## Cypress is agnostic to your apps
## backend language though.
language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules
    - ~/.cache

install:
  - npm install

script:
  # comment out for now - Cypress v3.1.1 should have better TS definition for jQuery
  # to pass linting
  # - npm run lint
  - npm run cypress:run
